<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>bifeldy_lib_90</RootNamespace>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <!-- Build Info -->
        <Version>1.0.0.0</Version>
        <SourceRevisionId>build$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss:fffZ"))</SourceRevisionId>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
